### PR TITLE
Contributing a working (CentOS7 + PE 3.8.1) systemd service script fo…

### PR DESCRIPTION
**Pull request by cvquesty**
…r evaluation.

I was trying to get the webhook working over CentOS 7.  By utilizing tom's contributions, what Zack already had in the pipe, and then some systemd documentation, I was able to get a systemctl script that starts the webhook daemon every time.  I cannot seem to get control over the process to kill, however, and could certainly use some help on that.

### CODE REVIEW

**Comment by acidprime** [comment]
Closed in favor of
https://github.com/acidprime/r10k/commit/efe8eb068d5e8d43a146cd63d184e9fa52d4f86f

**Comment by acidprime** [comment]
@cvquesty released in https://github.com/acidprime/r10k/releases/tag/v2.8.2 on the forge and here

**Comment by cvquesty** [comment]
Hey Zack…

Is there a story around naming the various things “rehat” rather than “redhat”?

Just curious.  All the templates, params, etc. are matched, I just found it humorous.



Jerald Sheets
questy@gmail.com

**Comment by acidprime** [comment]
@cvquesty can you detail the symptoms a little more? we keep flip flopping between commits on this.

**Pull request closed without merging**
