### PR TITLE
Add postrun to r10k.yaml

### LINKED ISSUE #211: Feature Request: add a r10k postrun hook for directory environment cache invalidation
Hi there,

according to the docs, it is good common practice to set `environment_timeout = unlimited` in directory environments and on updates do things to tell the puppet master that code has changed.
(see http://docs.puppetlabs.com/puppet/4.1/reference/environments_configuring.html#environmenttimeout and older versions like http://docs.puppetlabs.com/puppet/3.8/reference/environments_configuring.html#environmenttimeout)

I would appreciate a script that handles this called by the r10k postrun. For now I would only enable the API call to Puppetserver (http://docs.puppetlabs.com/puppetserver/latest/admin-api/v1/environment-cache.html), but this could be extended to support passenger/rack deployments, too.

Shall I open a PR addressing this issue? Same thing with time slots as for #210... ;-)

### PR DESCRIPTION
**Pull request by poikilotherm**
Fixes #211.

This simply adds the `postrun` r10k configuration option to `r10k.yaml`.

You can choose a script for yourself, maybe provided by a profile etc.

### CODE REVIEW

**Comment by acidprime** [comment]
Specs failed, will take a look at this once they are passing

**Comment by poikilotherm** [comment]
Thanks for commenting. I'm currently on vacation, thus not currently working on this. This is a dumb Ruby 1.8 issue, as 1.8 is not serializing arrays in the way newer version does (and I hadn't it on radar).

**Comment by acidprime** [comment]
yeah this is the classic hash ruby 1.8.7 problem. I ended up not using `to_yaml` in the main ERB for this same reason.

**Comment by acidprime** [comment]
@poikilotherm I have pulled this in a way that will allow ruby 1.8.7 to work , closing.

**Pull request closed without merging**
